version: "3.7"
networks:
  merginmaps:

services:

  redis:
    platform: linux/amd64
    image: redis
    container_name: merginmaps-redis
    restart: always
    networks:
      - merginmaps
  
  server:
    platform: linux/amd64
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    container_name: merginmaps-server
    restart: always
    user: 901:999
    volumes:
      - /projects:/data
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - merginmaps
  
  web:
    platform: linux/amd64
    image: lutraconsulting/merginmaps-frontend:2023.6.1
    container_name: merginmaps-web
    restart: always
    depends_on:
      - server
    networks:
      - merginmaps
  
  proxy:
    platform: linux/amd64
    image: nginx
    container_name: merginmaps-proxy
    restart: always
    ports:
      - "5000:80"
    volumes:
      - /projects:/data
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - merginmaps
